package main

const suffix = "_msg_gen"

// tpl temp
const tpl = `
// Code generated by github.com/mohuishou/gen-const-msg DO NOT EDIT

// Package {{.pkg}} const code comment msg
package {{.pkg}}

// noErrorMsg if code is not found, GetMsg will return this
const noErrorMsg = "unknown error"

// messages get msg from const comment
var messages = map[{{.constType}}]string{
	{{range $key, $value := .comments}}
	{{$key}}: "{{$value}}",{{end}}
}

{{ if ne .constType "int" }}
// String return string
func (code {{.constType}}) String () string {
	return GetMsg(code)
}
{{ end }}

// GetMsg get error msg
func GetMsg(code {{.constType}}) string {
	var (
		msg string
		ok  bool
	)
	if msg, ok = messages[code]; !ok {
		msg = noErrorMsg
	}
	return msg
}
`

const mdTpl = `
# {{.pkg}} ErrCode Msg

| code | message |
|:----|:----|
{{- range $key, $value := .comments}}
| {{$key}} | {{$value}} | {{- end}}
`
